name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build executable with spec file
      run: |
        pyinstaller vn_tracker.spec
    
    - name: Get version info
      id: version
      shell: pwsh
      run: |
        if ($env:GITHUB_REF -match "refs/tags/(.*)") {
          $version = $matches[1]
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "IS_RELEASE=true" >> $env:GITHUB_OUTPUT
        } else {
          $short_sha = git rev-parse --short HEAD
          $version = "dev-$short_sha"
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "IS_RELEASE=false" >> $env:GITHUB_OUTPUT
        }
        echo "Building version: $version"
    
    - name: Rename executable
      run: |
        if (Test-Path "dist\vn_tracker.exe") {
          Move-Item "dist\vn_tracker.exe" "dist\VNTimeTracker-${{ steps.version.outputs.VERSION }}.exe"
        } else {
          Write-Error "vn_tracker.exe not found in dist folder"
          exit 1
        }
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VNTimeTracker-${{ steps.version.outputs.VERSION }}
        path: dist/VNTimeTracker-${{ steps.version.outputs.VERSION }}.exe
    
    - name: Create Release
      if: steps.version.outputs.IS_RELEASE == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: VNTimeTracker ${{ steps.version.outputs.VERSION }}
        files: dist/VNTimeTracker-${{ steps.version.outputs.VERSION }}.exe
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}